### ISSUE TITLE
Text updates on tutorials complete. Ready for translation

### ISSUE THREAD

**Issue by mariamsaeedi** [zooniverse/penguinwatch#104]
Final text updates on the tutorials have been completed and ready to be translated. 

Staged at https://www.penguinwatch.org/beta/#/classify

**Comment by eatyourgreens** [comment]
I've run the `update-locale` script on the `update-tutorial` branch.
@yshish new text should be available to be translated on translations.zooniverse.org now
```
asosxlap127:penguinwatch odonnell$ npm run deploy-locale

> penguins@0.0.1 deploy-locale /Users/odonnell/zooniverse/penguinwatch
> seed-translation --project penguin --env production

Found language file at /Users/odonnell/zooniverse/penguinwatch/lib/en-us.coffee
Seeding locale to production
Done
asosxlap127:penguinwatch odonnell$ 
```

**Comment by eatyourgreens** [comment]
Just heard back from @yshish that she's organising the new translations so I'm closing this.
