### ISSUE TITLE
en-us file incomplete or site not translating all strings properly

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/penguinwatch#58]
See http://www.penguinwatch.org/?lang=./translations/es.json

**Comment by eatyourgreens** [comment]
I've merged the translation branch into master on readymade. Bumped the version to 0.6.4.

I think all that's left that's hardcoded in English are the team page and the title of the science page.

**Comment by eatyourgreens** [comment]
Bumping this because I've added a couple of new keys to en-us.coffee.

Spanish version is being tested at penguinwatch.org/beta

@chrissnyder did you ever figure out why the team page text from en-us.coffee isn't showing up in the translations app?

**Comment by chrissnyder** [comment]
I'd hazard a guess in this case that it just needs to be seeded again. See something like https://github.com/zooniverse/Milky-Way-Project/blob/master/package.json#L24

**Comment by eatyourgreens** [comment]
Cheers @chrissnyder that did the trick. New keys available to translate at http://translations.zooniverse.org/#/projects/penguin
