### ISSUE TITLE
please change text for landing page?

### ISSUE THREAD

**Issue by penguintom79** [zooniverse/penguinwatch#86]
Suggested text:

Welcome to PenguinWatch 2.0!

We now monitor over 100 sites! We need your help more than ever - to help monitor penguins, click "get started". If you are a school or educational site and you want to adopt and help us with a specific colony and get data feedbacks, please register (sign up) and contact us!

**Comment by astopy** [comment]
@penguintom79 This has been added in English now (thanks to @eatyourgreens). Ideally we'll want to add it in other languages too, assuming this will be a permanent change?

**Comment by yshish** [comment]
Nice! Where can I put the Czech translation for the new text? It is missing in the Translation page for PW. It would be good to add it there for other languages too. Thanks.

**Comment by eatyourgreens** [comment]
Hi @yshish The new text is showing up for me when I look at the translation page, under Todo. It was only added about 30 minutes ago, so maybe try reloading the page?

**Comment by yshish** [comment]
@eatyourgreens Oh, indeed! Thanks. I was looking under the Missing ones only 0:)

Going to translate it tonight.

**Comment by penguintom79** [comment]
Thanks!


Dr Tom Hart, Penguinologist.
Department of Zoology,
South Parks Road,
Oxford,
OX1 3PS.

+44 1865 600 170

www.penguinwatch.org<http://www.penguinwatch.org/>
www.penguinlifelines.org<http://www.penguinlifelines.org/>

**Comment by yshish** [comment]
May I ask what changes have been made to the Science page text that it appears under TODO as well? I haven't found any differences between the English and Czech versions, thanks.

**Comment by yshish** [comment]
BTW, the new text is ready to be published. I have already translated it.

**Comment by eatyourgreens** [comment]
Thanks @yshish New text should be on the site now. No changes to the Science page, as far as I know.

**Comment by yshish** [comment]
Then, shall I 'save' the translation for the Science page again, so it got away from the Todo? Or rather not?
