### ISSUE TITLE
scale down public/camera-setup.jpg

### ISSUE THREAD

**Issue by astopy** [zooniverse/penguinwatch#89]
[camera-setup.jpg](https://github.com/zooniverse/penguinwatch/blob/master/public/camera-setup.jpg) is pretty huge, and is loaded by every person who visits the site. Last month it accounted for 4.8 TB of our outgoing data transfer.

I'm not sure if we want to keep the full image in this repo and just scale it on deploy. @eatyourgreens What do you think?

**Comment by penguintom79** [comment]
Hi Adam,
Let’s reduce it then- no need to have the full version.
Cheers,
TOm


Dr Tom Hart, Penguinologist.
Department of Zoology,
South Parks Road,
Oxford,
OX1 3PS.

+44 1865 600 170

www.penguinwatch.org<http://www.penguinwatch.org/>
www.penguinlifelines.org<http://www.penguinlifelines.org/>
